### ISSUE TITLE
How to configure the top bar

### ISSUE THREAD

**Issue by rainer2208** [arcolinux/arcolinux-chadwm#1]
Hello, I am playing around with chadwm. Very a nice tool ... :-)

I could configure a lot of elements in the config file, but I am unable to add or delete elements from the top bar.

I found the bar.sh file , but changing anything there and compiling doesn't seem to have any visible impact.

Is this the correct file to look at? Seems the modifications get applied when changing the bar file in the original [project](https://github.com/siduck/chadwm). 

Could this be a compilation problem?

**Comment by arcolinuxz** [comment]
just a reboot problem

**Comment by rainer2208** [comment]
:-)  I did the reboot, but the layout only changes after i manually run bar.sh from the terminal  

this is actually strange ... when I log into chadwm from the desktop, my new configuration isn't there (even after reboot), only when i run the bar.sh script file ....

**Comment by arcolinuxz** [comment]
look at your code in /etc/skel

we kill bar.sh with pkill

**Comment by rainer2208** [comment]
why would you want to kill my bar ? :-)

**Comment by arcolinuxz** [comment]
because it stays in the memory and then you think nothing changed
