### ISSUE TITLE
chadwm not launching

### ISSUE THREAD

**Issue by XxRiKxX** [arcolinux/arcolinux-chadwm#2]
I watched one of your videos and changed the shell to bash and it still dont launch. On the sddm screen, i enter the password and I am back again the sddm. the xfce is launching fine

**Comment by arcolinuxz** [comment]
we have changed our config to make sure we can boot into zsh
bash was never a problem
compare

**Comment by XxRiKxX** [comment]
then why is this happening?

**Comment by arcolinuxz** [comment]
I have given the solution
compare your code with ours
compare your packages with ours
no virtualbox or similar
no nvidia drivers
...
